Switched implmentation of pbi_tmpnam to use mktemp. The latest GCC flags tmpnam as depricated with the following error:
error: 'tmpnam' is deprecated: This function
      is provided for compatibility reasons only. Due to security concerns
      inherent in the design of tmpnam(3), it is highly recommended that you use
      mkstemp(3) instead. [-Werror,-Wdeprecated-declarations]